Task 5.2 Refactored to make line chart reusable
ckp8/mashup pull request #46
Opened 2023-02-07 14:48 UTC by michaelcairney

https://docs.google.com/document/d/1IuF05cD8HyHdfLBfipF0PnwF95ExcMBJNyyRiNFWNzw/edit#heading=h.ikyqfua7q9ao

2023-02-07 15:24 UTC, Rinhammar requested changes
A couple of things:
1. The labels don't match the design in all of the charts. For example, in "Loan Amount", the labels should be: $1b, $750m, $500m, $250m and 0.
2. Also, you need to adjust the margin on the left side of the y-labels and the margin on the right side as well. 

Yours:
![image](https://user-images.githubusercontent.com/81630177/217286495-e0872cc0-d4f4-43e0-8e88-d73bf8aec216.png)

The design:
![image](https://user-images.githubusercontent.com/81630177/217285824-fdfcc5d6-11fc-48cc-bdcb-3bbfcab7cdaa.png)

2023-02-07 16:36 UTC, michaelcairney commented
> A couple of things:
> 
> 1. The labels don't match the design in all of the charts. For example, in "Loan Amount", the labels should be: $1b, $750m, $500m, $250m and 0.
> 2. Also, you need to adjust the margin on the left side of the y-labels and the margin on the right side as well.
> 
> Yours: ![image](https://user-images.githubusercontent.com/81630177/217286495-e0872cc0-d4f4-43e0-8e88-d73bf8aec216.png)
> 
> The design: ![image](https://user-images.githubusercontent.com/81630177/217285824-fdfcc5d6-11fc-48cc-bdcb-3bbfcab7cdaa.png)

Thanks I will sort the out the margins and remove the symbols from 0 🙂 
In regards to the labels we are going to be using real data (hopefully) soon, so I think every chart is going to change and be different from the labels/graphs in the design anyway

2023-02-07 16:38 UTC, Rinhammar commented
> > A couple of things:
> > 
> > 1. The labels don't match the design in all of the charts. For example, in "Loan Amount", the labels should be: $1b, $750m, $500m, $250m and 0.
> > 2. Also, you need to adjust the margin on the left side of the y-labels and the margin on the right side as well.
> > 
> > Yours: ![image](https://user-images.githubusercontent.com/81630177/217286495-e0872cc0-d4f4-43e0-8e88-d73bf8aec216.png)
> > The design: ![image](https://user-images.githubusercontent.com/81630177/217285824-fdfcc5d6-11fc-48cc-bdcb-3bbfcab7cdaa.png)
> 
> Thanks I will sort the out the margins and remove the symbols from 0 🙂 In regards to the labels we are going to be using real data (hopefully) soon, so I think every chart is going to change and be different from the labels/graphs in the design anyway, so hardcoding the axis values wouldn't make sense

Yes, that makes sense. Let's not hardcode the labels now then.

2023-02-10 10:19 UTC, Rinhammar approved these changes

2023-02-10 15:04 UTC, ckp8 approved these changes

2023-02-10 15:07 UTC, merged