table
ckp8/mashup pull request #49
Opened 2023-02-08 15:29 UTC by ckp8

dont review yet :)

2023-02-13 14:49 UTC, ckp8 commented
> 

Hi, I have fixed the dropdown however the  page selector is already being displayed on the right hand side for me

2023-02-14 15:06 UTC, Rinhammar commented
> > 
> 
> Hi, I have fixed the dropdown however the page selector is already being displayed on the right hand side for me

I've gone ahead and fixed this. The problem was that the divs had a fixed left value, meaning that they would always be in the same position no matter what screen size. On your screen it was aligned correctly, but it wouldn't necessarily do that for other screens. I made it so that it always aligns the same distance from the right side. Have a look at this if you want to see how I did it.

2023-02-14 16:54 UTC, michaelcairney requested changes

2023-02-14 16:57 UTC, michaelcairney reviewed
The '10 per page' dropwdown also seems to throw a white screen when clicked

2023-02-14 16:59 UTC, michaelcairney commented on src/data/CustomData.js
> +      LoanAmount:'$100M',
Would you be able to change the key names of the data here to match the values? E.g. change 'date' to 'currency'.
Also I think having them in order of how you want them to be displayed will help

2023-02-17 09:30 UTC, michaelcairney requested changes
Hi sorry to be annoying there's just a few more issues, great job so far though

2023-02-17 09:30 UTC, michaelcairney commented on src/pages/reporting/Ics/Table.jsx
> +          dropdownOptions={dropdownOptions}
There are duplicated `dropdownOptions` here

2023-02-17 09:30 UTC, michaelcairney commented on src/data/CustomData.js
> +      LoanAmount:'$100M',
So it looks like the headers in the table don't match the columns
![image](https://user-images.githubusercontent.com/98390672/219605940-aefc25ef-cfb1-4d0f-a3c5-2713bedf29a6.png)

 I'm thinking the best way to deal with this is to rename the key names in the data itself to the actual header names and in the order in the design that way it's a lot less likely for them to be mixed up, so:
```
{
"Account Number": '1234561'
"Account Currency": 'USD'
"Location - Country": 'USA'
... 
}
```
Then in the table component you can extract the array of headers with `Objects.keys(data[0])` and pass it into the header row component.

2023-02-17 09:30 UTC, michaelcairney commented on src/pages/reporting/Ics/AccountRepTableHeader.jsx
> +             {[i]}
I think it's best practice to be a bit more descriptive here so instead of just `i` could you put something like `headerName`

2023-02-17 09:30 UTC, michaelcairney commented on src/pages/reporting/Ics/AccountRepTableRow.jsx
> +      ))}
This is my bad apologies I got mixed up on previous review, could we rename 
`item` to  `row`,
`rowHeaders` to `rowNames`,
and `header` to `name`?
Or something similar that makes sense to you

2023-02-17 10:03 UTC, michaelcairney requested changes

2023-02-17 10:03 UTC, michaelcairney commented on src/data/CustomData.js
> +
Okay so what I meant was changing the key names to exactly what we want the headers in the table to be, so if you reference the design document and the headers there to make each data object like:
```
{
"Account Number": '1234561'
"Account Currency": 'USD'
"Location - Country": 'USA'
... 
}
```
and so on, then below I'll add a comment for the Table component

2023-02-17 10:03 UTC, michaelcairney commented on src/pages/reporting/Ics/Table.jsx
>          <AccountRepTableHeader headerTitle={headerTitle} />
Then I would extract the header names you've just updated out of `data` and plug them into the `AccountRepTableHeader` here

2023-02-17 10:34 UTC, michaelcairney approved these changes
Perfect, nicely done 👍

2023-02-17 11:09 UTC, Rinhammar approved these changes

2023-02-17 11:39 UTC, merged