Task 4.2.2
ckp8/mashup pull request #52
Opened 2023-02-10 16:47 UTC by ckp8

2023-02-14 15:53 UTC, Rinhammar reviewed
I am not sure what has happened here. It's not showing anything in the chart. Maybe take a look at how @michaelcairney did it in this PR: https://github.com/ckp8/mashup/pull/51.

![image](https://user-images.githubusercontent.com/81630177/218788810-f193df4a-6d3b-4956-9f18-77ad127b973f.png)

2023-02-17 15:57 UTC, Rinhammar requested changes
This is what the chart looks like for me. Missing y-axis, x-axis and all text.

![image](https://user-images.githubusercontent.com/81630177/219702654-f0087db1-305d-4912-915e-83b01af30d0b.png)

2023-02-17 15:58 UTC, ckp8 commented
> This is what the chart looks like for me. Missing y-axis, x-axis and all text.
> 
> ![image](https://user-images.githubusercontent.com/81630177/219702654-f0087db1-305d-4912-915e-83b01af30d0b.png)

interesting, thats not how its being shown to me

2023-02-17 16:17 UTC, michaelcairney commented on src/pages/homePage/totalPosition/Chart.jsx
>          <>
If you get rid of the conditional render for `dimensions` should fix it

2023-02-17 16:25 UTC, michaelcairney reviewed
Good work, I think first could you merge with main and implement the YAxis and XAxis components in the components folder into the chart and also if you could remove anything that you've commented out that is no longer necessary, thanks

2023-02-20 09:20 UTC, michaelcairney requested changes
Just need to add 
```
tickCount={5}
showGrid={true}
hideAxisLine={true}
```
to YAxis and 
```
hideAxisLine={true}
```
to XAxis

2023-02-20 09:58 UTC, michaelcairney approved these changes

2023-02-20 15:39 UTC, Rinhammar approved these changes
Made some very minor styling changes. Otherwise, good job! Also, labels on the y-axis might need to be changed in the future, depending on what data we have then.

2023-02-20 15:40 UTC, merged